---
# tasks to complete before running roles
- name: Update package cache
  hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: Update package cache (Arch)
      tags: always
      changed_when: False
      when: ansible_distribution == "Archlinux"
      community.general.pacman:
        update_cache: yes

    - name: Update package cache (Debian, etc)
      tags: always
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]
      ansible.builtin.apt:
        update_cache: yes

# run roles

- name: Installing packages for all hosts
  hosts: all
  become: true # become = become superuser
  tasks:
    - name: Install essential packages with default package manager
      ansible.builtin.package:
        name:
          - alacritty
          - cronie
          - ansible
          - ansible-lint
          - discord
          - git
          - git-delta
          - git-lfs
          - htop
          - ksysguard
          - tmux
          - less
          - mpv
          - qbittorrent
          - youtube-dl
        state: present

- name: Automatically pull changes from Git repository
  hosts: all
  become: true
  tasks:
    - name: Make sure we have a 'wheel' group
      ansible.builtin.group:
        name: wheel
        state: present
    - name: Allow 'wheel' group to have passwordless sudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    - name: Add sudoers users to wheel group
      ansible.builtin.user:
        name: velociraptor
        groups: wheel
        append: yes
        state: present
        create_home: no
    - name: Add ansible-pull cronjob
      ansible.builtin.cron:
        name: Ansible auto-provision every 10 minutes
        user: velociraptor
        minute: "*/10"
        job: >
          ansible-pull -o
          -U https://github.com/illiiilli/ansible_pull_rice.git

- name: Drive configuration for phoenixlinux
  hosts: phoenixlinux
  become: true
  tasks:
    - name: Mount Network Drive
      ansible.posix.mount:
        path: /network1
        src: UUID=32E61FC7E61F8A6D
        fstype: ntfs
        state: mounted

- name: End of run cleanup and reporting
  hosts: all
  become: true
  tasks:
    - name: Cleanup package cache (Debian and Ubuntu based only)
      tags: always
      ansible.builtin.apt:
        autoclean: yes
      changed_when: false
      when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

    - name: Autoremove orphan packages (Debian and Ubuntu based only)
      tags: always
      ansible.builtin.apt:
        autoremove: yes
        purge: yes
      when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

  # - name: send completion alert
  #   include_tasks: playbooks/send_completion_alert.yml
  #   tags: always
  #   when:
  #     - task_failed is not defined

  # - name: send failure alert
  #   include_tasks: playbooks/send_failure_alert.yml
  #   tags: always
  #   when:
  #     - task_failed is defined
  #     - task_failed == true
